{"name": "Создание пользователя без должности", "status": "broken", "statusDetails": {"message": "httpx.ConnectTimeout: _ssl.c:1003: The handshake operation timed out", "trace": "@contextlib.contextmanager\n    def map_httpcore_exceptions() -> typing.Iterator[None]:\n        global HTTPCORE_EXC_MAP\n        if len(HTTPCORE_EXC_MAP) == 0:\n            HTTPCORE_EXC_MAP = _load_httpcore_exceptions()\n        try:\n>           yield\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_transports\\default.py:101: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_transports\\default.py:250: in handle_request\n    resp = self._pool.handle_request(req)\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpcore\\_sync\\connection_pool.py:256: in handle_request\n    raise exc from None\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpcore\\_sync\\connection_pool.py:236: in handle_request\n    response = connection.handle_request(\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpcore\\_sync\\connection.py:101: in handle_request\n    raise exc\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpcore\\_sync\\connection.py:78: in handle_request\n    stream = self._connect(request)\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpcore\\_sync\\connection.py:156: in _connect\n    stream = stream.start_tls(**kwargs)\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpcore\\_backends\\sync.py:154: in start_tls\n    with map_exceptions(exc_map):\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\contextlib.py:162: in __exit__\n    self.gen.throw(value)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nmap = {<class 'TimeoutError'>: <class 'httpcore.ConnectTimeout'>, <class 'OSError'>: <class 'httpcore.ConnectError'>}\n\n    @contextlib.contextmanager\n    def map_exceptions(map: ExceptionMapping) -> typing.Iterator[None]:\n        try:\n            yield\n        except Exception as exc:  # noqa: PIE786\n            for from_exc, to_exc in map.items():\n                if isinstance(exc, from_exc):\n>                   raise to_exc(exc) from exc\nE                   httpcore.ConnectTimeout: _ssl.c:1003: The handshake operation timed out\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpcore\\_exceptions.py:14: ConnectTimeout\n\nThe above exception was the direct cause of the following exception:\n\n    @allure.suite('Тесты создания пользователей')\n    @allure.title('Создание пользователя без должности')\n    def test_create_user_without_job():\n        body = {\n            \"name\": \"morpheus\"\n        }\n        with allure.step(\"Отправляем POST-запрос для создания пользователя\"):\n>           response = httpx.post(BASE_URL + CREATE_USER, json=body)\n\ntests\\test_work_with_user_data.py:61: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_api.py:304: in post\n    return request(\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_api.py:109: in request\n    return client.request(\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_client.py:825: in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_client.py:914: in send\n    response = self._send_handling_auth(\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_client.py:942: in _send_handling_auth\n    response = self._send_handling_redirects(\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_client.py:979: in _send_handling_redirects\n    response = self._send_single_request(request)\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_client.py:1014: in _send_single_request\n    response = transport.handle_request(request)\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_transports\\default.py:249: in handle_request\n    with map_httpcore_exceptions():\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\contextlib.py:162: in __exit__\n    self.gen.throw(value)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @contextlib.contextmanager\n    def map_httpcore_exceptions() -> typing.Iterator[None]:\n        global HTTPCORE_EXC_MAP\n        if len(HTTPCORE_EXC_MAP) == 0:\n            HTTPCORE_EXC_MAP = _load_httpcore_exceptions()\n        try:\n            yield\n        except Exception as exc:\n            mapped_exc = None\n    \n            for from_exc, to_exc in HTTPCORE_EXC_MAP.items():\n                if not isinstance(exc, from_exc):\n                    continue\n                # We want to map to the most specific exception we can find.\n                # Eg if `exc` is an `httpcore.ReadTimeout`, we want to map to\n                # `httpx.ReadTimeout`, not just `httpx.TimeoutException`.\n                if mapped_exc is None or issubclass(to_exc, mapped_exc):\n                    mapped_exc = to_exc\n    \n            if mapped_exc is None:  # pragma: no cover\n                raise\n    \n            message = str(exc)\n>           raise mapped_exc(message) from exc\nE           httpx.ConnectTimeout: _ssl.c:1003: The handshake operation timed out\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_transports\\default.py:118: ConnectTimeout"}, "steps": [{"name": "Отправляем POST-запрос для создания пользователя", "status": "broken", "statusDetails": {"message": "httpx.ConnectTimeout: _ssl.c:1003: The handshake operation timed out\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\ApiTests\\tests\\test_work_with_user_data.py\", line 61, in test_create_user_without_job\n    response = httpx.post(BASE_URL + CREATE_USER, json=body)\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_api.py\", line 304, in post\n    return request(\n        \"POST\",\n    ...<13 lines>...\n        trust_env=trust_env,\n    )\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_api.py\", line 109, in request\n    return client.request(\n           ~~~~~~~~~~~~~~^\n        method=method,\n        ^^^^^^^^^^^^^^\n    ...<8 lines>...\n        follow_redirects=follow_redirects,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_client.py\", line 825, in request\n    return self.send(request, auth=auth, follow_redirects=follow_redirects)\n           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_client.py\", line 914, in send\n    response = self._send_handling_auth(\n        request,\n    ...<2 lines>...\n        history=[],\n    )\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_client.py\", line 942, in _send_handling_auth\n    response = self._send_handling_redirects(\n        request,\n        follow_redirects=follow_redirects,\n        history=history,\n    )\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_client.py\", line 979, in _send_handling_redirects\n    response = self._send_single_request(request)\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_client.py\", line 1014, in _send_single_request\n    response = transport.handle_request(request)\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 249, in handle_request\n    with map_httpcore_exceptions():\n         ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\contextlib.py\", line 162, in __exit__\n    self.gen.throw(value)\n    ~~~~~~~~~~~~~~^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 118, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\n"}, "start": 1736447510552, "stop": 1736447519459}], "start": 1736447510551, "stop": 1736447519467, "uuid": "08c13ce5-21b6-41e1-af89-8562a1bf74a1", "historyId": "c27b055dd7ee9cb50b58fe787bd92d16", "testCaseId": "c27b055dd7ee9cb50b58fe787bd92d16", "fullName": "tests.test_work_with_user_data#test_create_user_without_job", "labels": [{"name": "suite", "value": "Тесты создания пользователей"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "WIN-L0M9L8LCB9P"}, {"name": "thread", "value": "20820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_work_with_user_data"}]}